import {
  ClinicSettings,
  User,
  Doctor,
  Procedure,
  Medicine,
  Supplier,
  MedicineBatch,
  Patient,
  Invoice,
  StockTransaction,
  AuditLog,
} from '../types';

export const initialClinicSettings: ClinicSettings = {
  clinicName: 'Dr. Unnati Skin Clinic',
  tagline: 'Advanced Cosmetology, Laser & Aesthetic Care',
  logoUrl: '/logo.png',
  address: '204-205, Sahara Complex, Near Mahadev Temple, Wadhwan Road, Surendranagar, Gujarat - 363002',
  phone: '+91 98795 12345 / +91 02752 245678',
  email: 'contact@drunnatiskinclinic.com',
  gstin: '24AAACD1234F1Z8',
  registrationNo: 'GMC-64821',
  opdPrefix: 'OPD',
  prcPrefix: 'PRC',
  medPrefix: 'MED',
  defaultOpdTax: 0,
  defaultProcTax: 18,
  financialYear: '2526',
  termsAndConditions: '1. Fees once paid are non-refundable.\n2. Please carry this invoice for follow-up visits.\n3. Prescribed medicines must be taken strictly as per doctor instruction.',
};

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Dr. Unnati Suthar',
    email: 'unnati@drunnatiskinclinic.com',
    role: 'admin',
    isActive: true,
    phone: '+91 98795 12345',
  },
  {
    id: 'usr-2',
    name: 'Dr. Saurabh Suthar',
    email: 'saurabh@drunnatiskinclinic.com',
    role: 'doctor',
    isActive: true,
    phone: '+91 98795 54321',
  },
  {
    id: 'usr-3',
    name: 'Priya Patel',
    email: 'reception@drunnatiskinclinic.com',
    role: 'receptionist',
    isActive: true,
    phone: '+91 94280 11223',
  },
  {
    id: 'usr-4',
    name: 'Rajesh Shah',
    email: 'pharmacy@drunnatiskinclinic.com',
    role: 'pharmacist',
    isActive: true,
    phone: '+91 98980 99887',
  },
];

export const initialDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Unnati Suthar',
    specialization: 'Cosmetologist & Aesthetic Specialist',
    registrationNo: 'GMC-64821',
    defaultFee: 800,
    phone: '+91 98795 12345',
    email: 'unnati@drunnatiskinclinic.com',
  },
  {
    id: 'doc-2',
    name: 'Dr. Saurabh Suthar',
    specialization: 'MS (Gen. Surgery) & Aesthetic Laser Specialist',
    registrationNo: 'GMC-71045',
    defaultFee: 700,
    phone: '+91 98795 54321',
    email: 'saurabh@drunnatiskinclinic.com',
  },
];

export const initialProcedures: Procedure[] = [
  {
    id: 'prc-1',
    name: 'Carbon Laser Hollywood Peel',
    category: 'Laser Therapy',
    basePrice: 3500,
    description: 'Q-switched Nd:YAG laser peel for instant skin glow, pore tightening, and deep exfoliation.',
  },
  {
    id: 'prc-2',
    name: 'Fractional CO2 Laser Resurfacing',
    category: 'Laser Therapy',
    basePrice: 6500,
    description: 'Advanced resurfacing for deep acne scars, skin texture refinement, and collagen building.',
  },
  {
    id: 'prc-3',
    name: 'Hydrafacial & Glow Infusion',
    category: 'Facial Cosmetology',
    basePrice: 2800,
    description: '3-step medical grade facial with vortex extraction and hyaluronic acid hydration.',
  },
  {
    id: 'prc-4',
    name: 'Salicylic & Glycolic Acne Peel',
    category: 'Chemical Peel',
    basePrice: 2200,
    description: 'Targeted chemical exfoliation for active acne, comedones, and post-acne hyperpigmentation.',
  },
  {
    id: 'prc-5',
    name: 'Microneedling RF (MNRF) Acne Scar Session',
    category: 'Micro-needling',
    basePrice: 5000,
    description: 'Radiofrequency microneedling for collagen remodeling and acne scar smoothing.',
  },
  {
    id: 'prc-6',
    name: 'PRP Therapy for Hair Loss (Scalp)',
    category: 'Trichology',
    basePrice: 4500,
    description: 'Platelet-Rich Plasma scalp micro-injections for hair follicle regeneration.',
  },
  {
    id: 'prc-7',
    name: 'Botox Line Smoothing (Per Unit)',
    category: 'Botox & Fillers',
    basePrice: 450,
    description: 'FDA-approved botulinum toxin injection for forehead lines and crow feet.',
  },
  {
    id: 'prc-8',
    name: 'RF Skin Tag & Mole Removal',
    category: 'Minor Surgery',
    basePrice: 1800,
    description: 'Radiofrequency electrosurgical excision of benign skin tags and DPNs.',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Sun Pharma Laboratories Ltd.',
    contactPerson: 'Karan Mehta',
    phone: '+91 98250 88990',
    gstin: '27AABCS1423E1ZE',
    address: 'Sun House, Goregaon East, Mumbai, Maharashtra - 400063',
  },
  {
    id: 'sup-2',
    name: 'Cipla Cosmetology Division',
    contactPerson: 'Amit Trivedi',
    phone: '+91 98790 33445',
    gstin: '24AAACC1209B1ZA',
    address: 'Ellisbridge, Ashram Road, Ahmedabad, Gujarat - 380006',
  },
  {
    id: 'sup-3',
    name: 'Glenmark Pharmaceuticals',
    contactPerson: 'Nikhil Shah',
    phone: '+91 99090 77665',
    gstin: '24AAACG3401F1Z1',
    address: 'Alkapuri, Vadodara, Gujarat - 390007',
  },
  {
    id: 'sup-4',
    name: 'CosmoCare Pharma Distributors',
    contactPerson: 'Sanjay Patel',
    phone: '+91 98240 12121',
    gstin: '24AABFD8832K1ZP',
    address: 'Main Market, Surendranagar, Gujarat - 363001',
  },
];

export const initialMedicines: Medicine[] = [
  {
    id: 'med-1',
    name: 'Tretinoin 0.05% Cream (20g)',
    genericName: 'Tretinoin USP',
    category: 'Topical Creams & Ointments',
    manufacturer: 'Sun Pharma',
    unit: 'Tube',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 15,
  },
  {
    id: 'med-2',
    name: 'Glycolic Acid 10% Foaming Face Wash (100ml)',
    genericName: 'Glycolic Acid + AHA Cleanser',
    category: 'Cleansers & Washes',
    manufacturer: 'Cipla Cosmo',
    unit: 'Bottle',
    hsnCode: '330499',
    gstRate: 18,
    reorderLevel: 10,
  },
  {
    id: 'med-3',
    name: 'SPF 50+ PA++++ Aqua Gel Sunscreen (50g)',
    genericName: 'Broad Spectrum UV Shield Gel',
    category: 'Sunscreen & Serums',
    manufacturer: 'Glenmark',
    unit: 'Tube',
    hsnCode: '330499',
    gstRate: 18,
    reorderLevel: 20,
  },
  {
    id: 'med-4',
    name: 'Itraconazole 200mg Capsules',
    genericName: 'Itraconazole BP',
    category: 'Oral Antifungals',
    manufacturer: 'Cipla',
    unit: 'Strip (10 Caps)',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 15,
  },
  {
    id: 'med-5',
    name: 'Clindamycin 1% + Nicotinamide Gel (20g)',
    genericName: 'Clindamycin Phosphate + Niacinamide',
    category: 'Topical Creams & Ointments',
    manufacturer: 'Glenmark',
    unit: 'Tube',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 12,
  },
  {
    id: 'med-6',
    name: 'Minoxidil 5% + Finasteride 0.1% Solution (60ml)',
    genericName: 'Minoxidil & Finasteride Topical Serum',
    category: 'Hair Care',
    manufacturer: 'Sun Pharma',
    unit: 'Bottle',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 8,
  },
  {
    id: 'med-7',
    name: 'Vitamin C 20% Glow Serum (30ml)',
    genericName: 'L-Ascorbic Acid + Ferulic Acid',
    category: 'Sunscreen & Serums',
    manufacturer: 'CosmoCare',
    unit: 'Bottle',
    hsnCode: '330499',
    gstRate: 18,
    reorderLevel: 10,
  },
  {
    id: 'med-8',
    name: 'Hydroquinone 2% + Kojic Acid Cream (15g)',
    genericName: 'Depigmenting Triple Formula',
    category: 'Topical Creams & Ointments',
    manufacturer: 'Cipla Cosmo',
    unit: 'Tube',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 15,
  },
  {
    id: 'med-9',
    name: 'Doxycycline 100mg Capsules',
    genericName: 'Doxycycline Hyclate USP',
    category: 'Oral Antibiotics',
    manufacturer: 'Sun Pharma',
    unit: 'Strip (10 Caps)',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 20,
  },
  {
    id: 'med-10',
    name: 'Ceramide Hydrating Barrier Cream (50g)',
    genericName: 'Ceramide NP + Hyaluronic Acid Cream',
    category: 'Topical Creams & Ointments',
    manufacturer: 'Glenmark',
    unit: 'Jar',
    hsnCode: '330499',
    gstRate: 18,
    reorderLevel: 12,
  },
  {
    id: 'med-11',
    name: 'Azelaic Acid 15% Gel (30g)',
    genericName: 'Azelaic Acid Micronized',
    category: 'Topical Creams & Ointments',
    manufacturer: 'Cipla Cosmo',
    unit: 'Tube',
    hsnCode: '300490',
    gstRate: 12,
    reorderLevel: 10,
  },
  {
    id: 'med-12',
    name: 'Ketoconazole 2% Anti-Dandruff Shampoo (100ml)',
    genericName: 'Ketoconazole + Zinc Pyrithione',
    category: 'Hair Care',
    manufacturer: 'Sun Pharma',
    unit: 'Bottle',
    hsnCode: '330510',
    gstRate: 18,
    reorderLevel: 15,
  },
];

export const initialBatches: MedicineBatch[] = [
  // Tretinoin - Batch 1 near expiry (low stock) & Batch 2 fresh
  {
    id: 'btc-101',
    medicineId: 'med-1',
    batchNo: 'B-TRT2026',
    expiryDate: '2026-11-15', // Near expiry (~50 days)
    mrp: 260,
    purchasePrice: 160,
    sellingPrice: 240,
    quantityInStock: 8, // Low stock alert (<15)
    supplierId: 'sup-1',
    supplierName: 'Sun Pharma Laboratories Ltd.',
  },
  {
    id: 'btc-102',
    medicineId: 'med-1',
    batchNo: 'B-TRT2027',
    expiryDate: '2027-08-20',
    mrp: 260,
    purchasePrice: 160,
    sellingPrice: 240,
    quantityInStock: 45,
    supplierId: 'sup-1',
    supplierName: 'Sun Pharma Laboratories Ltd.',
  },
  // Glycolic Wash
  {
    id: 'btc-201',
    medicineId: 'med-2',
    batchNo: 'B-GLY882',
    expiryDate: '2027-05-10',
    mrp: 495,
    purchasePrice: 310,
    sellingPrice: 450,
    quantityInStock: 28,
    supplierId: 'sup-2',
    supplierName: 'Cipla Cosmetology Division',
  },
  // Sunscreen - Batch 1 critical expiry & low stock
  {
    id: 'btc-301',
    medicineId: 'med-3',
    batchNo: 'B-SUN901',
    expiryDate: '2026-10-25', // Expiring in ~29 days!
    mrp: 750,
    purchasePrice: 480,
    sellingPrice: 680,
    quantityInStock: 5, // Low stock alert (<20)
    supplierId: 'sup-3',
    supplierName: 'Glenmark Pharmaceuticals',
  },
  {
    id: 'btc-302',
    medicineId: 'med-3',
    batchNo: 'B-SUN902',
    expiryDate: '2027-12-30',
    mrp: 750,
    purchasePrice: 480,
    sellingPrice: 680,
    quantityInStock: 60,
    supplierId: 'sup-3',
    supplierName: 'Glenmark Pharmaceuticals',
  },
  // Itraconazole
  {
    id: 'btc-401',
    medicineId: 'med-4',
    batchNo: 'B-ITR441',
    expiryDate: '2027-03-15',
    mrp: 360,
    purchasePrice: 210,
    sellingPrice: 320,
    quantityInStock: 35,
    supplierId: 'sup-2',
    supplierName: 'Cipla Cosmetology Division',
  },
  // Clindamycin Gel - Expiring soon
  {
    id: 'btc-501',
    medicineId: 'med-5',
    batchNo: 'B-CLN102',
    expiryDate: '2026-11-01', // Expiring in ~36 days
    mrp: 198,
    purchasePrice: 115,
    sellingPrice: 180,
    quantityInStock: 18,
    supplierId: 'sup-3',
    supplierName: 'Glenmark Pharmaceuticals',
  },
  // Minoxidil
  {
    id: 'btc-601',
    medicineId: 'med-6',
    batchNo: 'B-MIN505',
    expiryDate: '2027-09-30',
    mrp: 890,
    purchasePrice: 540,
    sellingPrice: 790,
    quantityInStock: 14,
    supplierId: 'sup-1',
    supplierName: 'Sun Pharma Laboratories Ltd.',
  },
  // Vitamin C Serum
  {
    id: 'btc-701',
    medicineId: 'med-7',
    batchNo: 'B-VIT303',
    expiryDate: '2027-07-15',
    mrp: 1299,
    purchasePrice: 780,
    sellingPrice: 1150,
    quantityInStock: 22,
    supplierId: 'sup-4',
    supplierName: 'CosmoCare Pharma Distributors',
  },
  // Hydroquinone - Expiring & Low Stock
  {
    id: 'btc-801',
    medicineId: 'med-8',
    batchNo: 'B-HYD118',
    expiryDate: '2026-10-18', // Expiring in 22 days!
    mrp: 330,
    purchasePrice: 190,
    sellingPrice: 290,
    quantityInStock: 4, // Low stock alert (<15)
    supplierId: 'sup-2',
    supplierName: 'Cipla Cosmetology Division',
  },
  // Doxycycline
  {
    id: 'btc-901',
    medicineId: 'med-9',
    batchNo: 'B-DOX612',
    expiryDate: '2027-06-30',
    mrp: 165,
    purchasePrice: 85,
    sellingPrice: 140,
    quantityInStock: 75,
    supplierId: 'sup-1',
    supplierName: 'Sun Pharma Laboratories Ltd.',
  },
  // Ceramide Cream
  {
    id: 'btc-1001',
    medicineId: 'med-10',
    batchNo: 'B-CER220',
    expiryDate: '2027-11-20',
    mrp: 650,
    purchasePrice: 390,
    sellingPrice: 590,
    quantityInStock: 30,
    supplierId: 'sup-3',
    supplierName: 'Glenmark Pharmaceuticals',
  },
  // Azelaic Acid
  {
    id: 'btc-1101',
    medicineId: 'med-11',
    batchNo: 'B-AZA707',
    expiryDate: '2027-04-10',
    mrp: 425,
    purchasePrice: 250,
    sellingPrice: 380,
    quantityInStock: 16,
    supplierId: 'sup-2',
    supplierName: 'Cipla Cosmetology Division',
  },
  // Ketoconazole Shampoo
  {
    id: 'btc-1201',
    medicineId: 'med-12',
    batchNo: 'B-KET404',
    expiryDate: '2027-10-15',
    mrp: 310,
    purchasePrice: 170,
    sellingPrice: 275,
    quantityInStock: 32,
    supplierId: 'sup-1',
    supplierName: 'Sun Pharma Laboratories Ltd.',
  },
];

export const initialPatients: Patient[] = [
  {
    id: 'UNT-000101',
    fullName: 'Ananya Sharma',
    gender: 'Female',
    age: 28,
    dob: '1998-04-14',
    phone: '9825198251',
    email: 'ananya.sharma@example.com',
    address: 'Flat 302, Royal Palms Apartments, Wadhwan, Surendranagar',
    referredBy: 'Dr. R. K. Joshi',
    allergiesNotes: 'Allergic to Sulfa drugs. Sensitive facial skin prone to rosacea.',
    registeredAt: '2026-09-01T10:30:00Z',
  },
  {
    id: 'UNT-000102',
    fullName: 'Rajeshbhai Patel',
    gender: 'Male',
    age: 45,
    dob: '1981-08-22',
    phone: '9879012345',
    email: 'rajesh.patel@example.com',
    address: '12, Shanti Nagar Society, Ratanpar, Surendranagar',
    referredBy: 'Self / Google Search',
    allergiesNotes: 'No known drug allergies. Seeking treatment for androgenetic alopecia.',
    registeredAt: '2026-09-05T11:15:00Z',
  },
  {
    id: 'UNT-000103',
    fullName: 'Pooja V. Dabhi',
    gender: 'Female',
    age: 24,
    dob: '2002-12-05',
    phone: '9909988776',
    email: 'pooja.dabhi@example.com',
    address: 'B-14, Green Valley Bungalows, Dhrangadhra Highway',
    referredBy: 'Instagram Page',
    allergiesNotes: 'Hormonal acne grade 3, post-inflammatory hyperpigmentation.',
    registeredAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'UNT-000104',
    fullName: 'Manish Kumar Sonaiya',
    gender: 'Male',
    age: 36,
    dob: '1990-03-18',
    phone: '9426543210',
    email: 'manish.sonaiya@example.com',
    address: '45, Station Road, Limbdi, Surendranagar',
    referredBy: 'Dr. Unnati Suthar',
    allergiesNotes: 'Psoriasis plaques on elbows and knees.',
    registeredAt: '2026-09-18T09:45:00Z',
  },
  {
    id: 'UNT-000105',
    fullName: 'Manjulaben Sarvaiya',
    gender: 'Female',
    age: 52,
    dob: '1974-06-30',
    phone: '9879944556',
    email: '',
    address: 'Near Old Bus Stand, Wadhwan City',
    referredBy: 'Camp Referral',
    allergiesNotes: 'Melasma on cheeks, sensitive skin.',
    registeredAt: '2026-09-22T14:20:00Z',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-1001',
    invoiceNo: 'OPD-2526-0001',
    invoiceType: 'OPD',
    patientId: 'UNT-000101',
    patientName: 'Ananya Sharma',
    patientPhone: '9825198251',
    patientUHID: 'UNT-000101',
    patientAgeGender: '28 Yrs / Female',
    doctorId: 'doc-1',
    doctorName: 'Dr. Unnati Suthar',
    date: '2026-09-25T10:45:00Z',
    items: [
      {
        id: 'itm-1',
        invoiceId: 'inv-1001',
        description: 'OPD Cosmetology Consultation (Follow-up)',
        quantity: 1,
        unitPrice: 800,
        discount: 0,
        taxRate: 0,
        lineTotal: 800,
        sourceType: 'consultation',
      },
    ],
    subtotal: 800,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 800,
    paymentMode: 'UPI',
    paymentStatus: 'Paid',
    status: 'ACTIVE',
    createdBy: 'usr-3',
    creatorName: 'Priya Patel',
  },
  {
    id: 'inv-1002',
    invoiceNo: 'PRC-2526-0001',
    invoiceType: 'PROCEDURE',
    patientId: 'UNT-000103',
    patientName: 'Pooja V. Dabhi',
    patientPhone: '9909988776',
    patientUHID: 'UNT-000103',
    patientAgeGender: '24 Yrs / Female',
    doctorId: 'doc-1',
    doctorName: 'Dr. Unnati Suthar',
    date: '2026-09-25T14:30:00Z',
    items: [
      {
        id: 'itm-2',
        invoiceId: 'inv-1002',
        description: 'Carbon Laser Hollywood Peel',
        quantity: 1,
        unitPrice: 3500,
        discount: 350,
        taxRate: 18,
        lineTotal: 3717,
        sourceType: 'procedure',
        sessionNote: 'Session 1 of 4',
      },
    ],
    subtotal: 3500,
    discountTotal: 350,
    taxTotal: 567,
    grandTotal: 3717,
    paymentMode: 'Card',
    paymentStatus: 'Paid',
    status: 'ACTIVE',
    createdBy: 'usr-3',
    creatorName: 'Priya Patel',
  },
  {
    id: 'inv-1003',
    invoiceNo: 'MED-2526-0001',
    invoiceType: 'MEDICINE',
    patientId: 'UNT-000101',
    patientName: 'Ananya Sharma',
    patientPhone: '9825198251',
    patientUHID: 'UNT-000101',
    patientAgeGender: '28 Yrs / Female',
    doctorId: 'doc-1',
    doctorName: 'Dr. Unnati Suthar',
    date: '2026-09-26T11:15:00Z',
    items: [
      {
        id: 'itm-3',
        invoiceId: 'inv-1003',
        description: 'Tretinoin 0.05% Cream (20g) [Batch: B-TRT2026]',
        quantity: 2,
        unitPrice: 240,
        discount: 0,
        taxRate: 12,
        lineTotal: 537.6,
        sourceType: 'medicine',
        medicineId: 'med-1',
        medicineBatchId: 'btc-101',
        hsnCode: '300490',
      },
      {
        id: 'itm-4',
        invoiceId: 'inv-1003',
        description: 'SPF 50+ PA++++ Aqua Gel Sunscreen (50g) [Batch: B-SUN901]',
        quantity: 1,
        unitPrice: 680,
        discount: 0,
        taxRate: 18,
        lineTotal: 802.4,
        sourceType: 'medicine',
        medicineId: 'med-3',
        medicineBatchId: 'btc-301',
        hsnCode: '330499',
      },
    ],
    subtotal: 1160,
    discountTotal: 0,
    taxTotal: 180,
    grandTotal: 1340,
    paymentMode: 'UPI',
    paymentStatus: 'Paid',
    status: 'ACTIVE',
    createdBy: 'usr-4',
    creatorName: 'Rajesh Shah',
  },
];

export const initialStockTransactions: StockTransaction[] = [
  {
    id: 'stx-1',
    medicineId: 'med-1',
    medicineName: 'Tretinoin 0.05% Cream (20g)',
    batchId: 'btc-101',
    batchNo: 'B-TRT2026',
    type: 'IN',
    quantity: 10,
    date: '2026-09-01T09:00:00Z',
    userId: 'usr-4',
    userName: 'Rajesh Shah',
    remarks: 'Opening inventory stock receipt from Sun Pharma',
  },
  {
    id: 'stx-2',
    medicineId: 'med-1',
    medicineName: 'Tretinoin 0.05% Cream (20g)',
    batchId: 'btc-101',
    batchNo: 'B-TRT2026',
    type: 'OUT',
    quantity: 2,
    referenceInvoiceId: 'inv-1003',
    date: '2026-09-26T11:15:00Z',
    userId: 'usr-4',
    userName: 'Rajesh Shah',
    remarks: 'Billed in Pharmacy Invoice MED-2526-0001',
  },
  {
    id: 'stx-3',
    medicineId: 'med-3',
    medicineName: 'SPF 50+ PA++++ Aqua Gel Sunscreen (50g)',
    batchId: 'btc-301',
    batchNo: 'B-SUN901',
    type: 'OUT',
    quantity: 1,
    referenceInvoiceId: 'inv-1003',
    date: '2026-09-26T11:15:00Z',
    userId: 'usr-4',
    userName: 'Rajesh Shah',
    remarks: 'Billed in Pharmacy Invoice MED-2526-0001',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-1',
    userName: 'Dr. Unnati Suthar',
    action: 'SYSTEM_INIT',
    entity: 'ClinicSettings',
    entityId: 'settings-main',
    timestamp: '2026-09-26T08:00:00Z',
    afterState: 'Initialized clinic billing system with GST configurations',
  },
];
